### ISSUE TITLE
TypeError: Failed to fetch and Access to fetch has been blocked

### ISSUE THREAD

**Issue by jamesbraza** [ollama-ui/ollama-ui#11]
In one terminal, I have run:

```bash
> make download_resources
# Check if resources directory exists, if not create it
# Check SHA-256 hash
resources/bootstrap.bundle.min.js: OK
resources/bootstrap.min.css: OK
resources/marked.min.js: OK
resources/purify.min.js: OK
> ls resources                                                                                                                                   ok | 3.11.5 py | at 03:33:24 PM
bootstrap.bundle.min.js bootstrap.min.css       marked.min.js           purify.min.js
> ./ollama serve
2023/09/16 15:22:34 routes.go:536: Listening on 127.0.0.1:11434
...
```

In another terminal:

```bash
> make web_server
python3 -m http.server
Serving HTTP on :: port 8000 (http://[::]:8000/) ...
::ffff:127.0.0.1 - - [16/Sep/2023 15:32:15] "GET / HTTP/1.1" 304 -
::ffff:127.0.0.1 - - [16/Sep/2023 15:32:16] code 404, message File not found
::ffff:127.0.0.1 - - [16/Sep/2023 15:32:16] "GET /resources/bootstrap.bundle.min.js.map HTTP/1.1" 404 -
::ffff:127.0.0.1 - - [16/Sep/2023 15:32:16] code 404, message File not found
::ffff:127.0.0.1 - - [16/Sep/2023 15:32:16] "GET /resources/purify.min.js.map HTTP/1.1" 404 -
::ffff:127.0.0.1 - - [16/Sep/2023 15:32:16] code 404, message File not found
::ffff:127.0.0.1 - - [16/Sep/2023 15:32:16] "GET /resources/bootstrap.min.css.map HTTP/1.1" 404 -
```

The UI isn't working, there is no response.  Opening Chrome's developer tools:

![screenshot of Chrome dev tools](https://github.com/ollama-ui/ollama-ui/assets/8990777/ea86533e-6b83-4b8d-896c-c6b10f0464eb)

Any idea what's going on here?

**Comment by rtcfirefly** [comment]
Looks like you aren't connecting to localhost. What URL are you using?

**Comment by jamesbraza** [comment]
The URLs I was using:
- `ollama serve` was listening on `127.0.0.1` at port 11434
- `python3 -m http.server` was listening on `::` at port 8000, so I went to http://0.0.0.0:8000/

However, I see now that going to http://localhost:8000/ works fine 🥳 .

The only error I get now is with a favicon (opened https://github.com/ollama-ui/ollama-ui/issues/12 for this).

It seems that `localhost` works, but not `0.0.0.0`.  Is there anything we can do for this?  My apologies, but I am not super familiar with networking enough to know why `0.0.0.0` fails but `localhost` works.

**Comment by rtcfirefly** [comment]
@jamesbraza - I made this change to force the webserver onto localhost
https://github.com/ollama-ui/ollama-ui/commit/f39559bc71069124f917d4c5e7c1f9c86322b4ea

**Comment by jamesbraza** [comment]
Like it and good thinking
