### ISSUE TITLE
Request: working demo on GitHub Pages

### ISSUE THREAD

**Issue by jamesbraza** [ollama-ui/ollama-ui#15]
I happened to notice that there's GitHub pages: https://ollama-ui.github.io/ollama-ui/

Would be cool if it somehow worked, and was linked in the `README.md` and/or website field of repo details

**Comment by rtcfirefly** [comment]
Hi @jamesbraza, this should work now :)

You just need to run the following:
```
OLLAMA_ORIGINS=https://ollama-ui.github.io ollama serve
```

https://ollama-ui.github.io/ollama-ui/

**Comment by jamesbraza** [comment]
Ha that works, that's pretty cool how you can override a URL like that. Thanks for setting it up!

---

FYI my Mac with dark theme messes up default GitHub pages (no Ollama server running):

![screenshot of page with dark theme](https://github.com/ollama-ui/ollama-ui/assets/8990777/58646b1a-ccbc-461c-8803-c420871f534f)

---

In linking the FAQ, why did you choose to link the raw file https://raw.githubusercontent.com/jmorganca/ollama/main/docs/faq.md instead of the rendered file https://github.com/jmorganca/ollama/blob/main/docs/faq.md?

**Comment by jamesbraza** [comment]
It would be good to put the GitHub pages URL on the right of GitHub repo page

![image](https://github.com/ollama-ui/ollama-ui/assets/8990777/2058ffcb-d3b3-4e95-ab3b-34afba0a9df4)

Kind of like how [Ollama](https://github.com/jmorganca/ollama) has [ollama.ai](https://ollama.ai/) set up

![image](https://github.com/ollama-ui/ollama-ui/assets/8990777/3661fa6a-35ec-491e-ad40-755e2eb31209)

**Comment by rtcfirefly** [comment]
Thanks!
I've fixed up the colors, should look better now
Let me know if it looks ok for you

**Comment by jamesbraza** [comment]
Now answering from Chrome on Windows 10, it looks great

![screenshot of Windows 10 Chrome screen](https://github.com/ollama-ui/ollama-ui/assets/8990777/f300fe61-3e50-46f0-b195-815d38b44b40)

---

Feel free to close this out, thank you!

Out of curiosity, why use the raw `faq.md` link instead of rendered `faq.md` link?

**Comment by rtcfirefly** [comment]
Ah, good catch. I'll fix that
Thanks!
