### ISSUE TITLE
Chrome Extension seemingly broken

### ISSUE THREAD

**Issue by leobut** [ollama-ui/ollama-ui#16]
I am using Version 1.4 and this is what I get when I open the UI:

![Screenshot 2023-09-27 at 10 00 53](https://github.com/ollama-ui/ollama-ui/assets/9163917/45b633dd-da6e-4681-a975-1e85152b6959)

_Chrome 116.0.5845.187 on macOS 13.6_

**Comment by ollama-ui** [comment]
Sorry for the trouble, a fixed version is in review now.

I am also hosting the app here: https://ollama-ui.github.io/ollama-ui/

It's the same as the extension, but requires the following command to be run at the terminal:

```
OLLAMA_ORIGINS=https://ollama-ui.github.io ollama serve
```

**Comment by rtcfirefly** [comment]
@leobut - Should be fixed now 👍
