### ISSUE TITLE
Bug: GitHub Pages Hosted version doesn't work due to HTTPS violation

### ISSUE THREAD

**Issue by coolaj86** [ollama-ui/ollama-ui#26]
# Problem

> net::ERR_BLOCKED_BY_CLIENT

<img width="1108" alt="Screenshot 2023-10-21 at 11 40 54 AM" src="https://github.com/ollama-ui/ollama-ui/assets/122831/ec82c98f-6d2f-4072-8a57-04228aa5a4f3">

<img width="1056" alt="Screenshot 2023-10-21 at 11 41 47 AM" src="https://github.com/ollama-ui/ollama-ui/assets/122831/a47c0605-9a72-44ad-8548-13d5dc6f94f0">

The site at <https://ollama-ui.github.io/ollama-ui/> makes a request to <http://localhost:11434/api/tags> which are blocked BY THE CLIENT (not the server), for a few reasons:

### The request needs to be HTTPS

The hosted version should request <https://localhost:11443>, NOT <http://localhost:11434>.

### The localhost server should be valid HTTPS

This can be solve easily with certificates that are recognized by all web browsers by using [`caddy`](https://webinstall.dev/caddy)

1. Install `caddy`
   ```sh
   # Mac, Linux
   curl https://webi.sh/caddy | sh

   # Windows
   curl.exe https://webi.ms/caddy | powershell
   ```
2. Create a Reverse Proxy Caddyfile
   `./Caddyfile`:
   ```sh
   https://localhost:11443 {
       reverse_proxy localhost:11434
   }
   ```
3. Run caddy
   ```sh
   caddy run --config ./Caddyfile
   ```

## The `Origin` header is omitted for `localhost`

Running the ollama server with `OLLAMA_ORIGINS='https://github.com/ollama-ui/ollama-ui'` won't work because the `Origin` header isn't sent. Instead the wildcard must be used.

```sh
OLLAMA_HOST=0.0.0.0:11434 OLLAMA_ORIGINS='*' ollama serve
```

**Comment by rtcfirefly** [comment]
ah, interesting issue.

I'll see what I can do

**Comment by rtcfirefly** [comment]
Added the option to enter a custom URL to GitHub Pages Hosted version
