### ISSUE TITLE
Security: Chrome Extension requests access to ALL websites

### ISSUE THREAD

**Issue by coolaj86** [ollama-ui/ollama-ui#27]
This should only need to read from `localhost`, not ALL websites.

<img width="476" alt="Screenshot 2023-10-21 at 11 44 36 AM" src="https://github.com/ollama-ui/ollama-ui/assets/122831/a1254371-2b1b-4397-8070-1def98976b60">

**Comment by rtcfirefly** [comment]
Hi!

This was added to allow users to use a remote instance of ollama (i.e. not on localhost).

The manifest limits the extension as much as possible.

```
  "host_permissions": [
    "http://*:11434/api/tags",
    "http://*:11434/api/generate"
  ],
```

It's a shame the warning isn't a bit clearer, but there's not much we can do about that.

Happy to take fixes if you find one
