### ISSUE TITLE
Open Source?

### ISSUE THREAD

**Issue by swyxio** [ollama-ui/ollama-ui#9]
sorry to be annoying but i have no idea what the license is. mind picking one? [docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository)

**Comment by ollama-ui** [comment]
Following ollama project 
https://github.com/jmorganca/ollama/blob/main/LICENSE
